version: '3'

services:
  database-api:
    image: mysql:8.0
    networks:
      - fc
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-formerlychucks_api}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_USER:-password}
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql:rw
  s3:
    image: minio/minio
    container_name: s3
    networks:
      - fc
    entrypoint: sh
    command: -c 'mkdir -p /data/sneed && minio server --address 0.0.0.0:4040 --console-address 0.0.0.0:4041 /data && mc policy set download sneed'
    ports:
      - "4040:4040"
      - "4041:4041"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
  php-fpm:
    container_name: php-fpm
    networks:
      - fc
    build:
      context: ./docker/php-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/api
    depends_on:
      - database-api
  nginx-api:
    container_name: nginx-api
    image: nginx:stable-alpine
    networks:
      - fc
    ports:
      - '8181:8181'
    volumes:
      - ./:/var/www/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - database-api

volumes:
  db-data:

networks:
  fc:
    name: formerlychucks
    ipam:
      config:
        - subnet: 172.16.57.0/24